// Emoji keywords mapping for search functionality
export const EMOJI_KEYWORDS: Record<string, string[]> = {
  // Smileys & Emotion
  '😀': ['grinning', 'smile', 'happy', 'face'],
  '😃': ['smiley', 'happy', 'joy', 'face'],
  '😄': ['grin', 'smile', 'happy', 'face'],
  '😁': ['beaming', 'grin', 'smile', 'happy'],
  '😆': ['laughing', 'satisfied', 'happy', 'lol'],
  '😅': ['sweat', 'smile', 'nervous', 'relief'],
  '🤣': ['rofl', 'laughing', 'lol', 'funny'],
  '😂': ['joy', 'tears', 'laughing', 'lol', 'funny'],
  '🙂': ['slightly', 'smile', 'face'],
  '🙃': ['upside', 'down', 'sarcasm', 'irony'],
  '😉': ['wink', 'flirt', 'face'],
  '😊': ['blush', 'smile', 'happy', 'shy'],
  '😇': ['innocent', 'angel', 'halo', 'blessed'],
  '🥰': ['love', 'hearts', 'adore', 'affection'],
  '😍': ['heart', 'eyes', 'love', 'crush'],
  '🤩': ['star', 'struck', 'excited', 'wow'],
  '😘': ['kiss', 'love', 'heart', 'blow'],
  '😗': ['kiss', 'face', 'smooch'],
  '☺️': ['smiling', 'relaxed', 'blush'],
  '😚': ['kiss', 'closed', 'eyes', 'love'],
  '😙': ['kiss', 'smile', 'face'],
  '🥲': ['smiling', 'tear', 'sad', 'happy'],
  '😋': ['yummy', 'delicious', 'tongue', 'tasty'],
  '😛': ['tongue', 'playful', 'silly'],
  '😜': ['wink', 'tongue', 'crazy', 'playful'],
  '🤪': ['zany', 'crazy', 'wild', 'silly'],
  '😝': ['squinting', 'tongue', 'playful'],
  '🤑': ['money', 'rich', 'dollar', 'greedy'],
  '🤗': ['hug', 'hugging', 'embrace', 'love'],
  '🤭': ['giggle', 'shy', 'cover', 'oops'],
  '🤫': ['shush', 'quiet', 'secret', 'silence'],
  '🤔': ['think', 'thinking', 'hmm', 'consider'],
  '🤐': ['zipper', 'mouth', 'secret', 'quiet'],
  '🤨': ['raised', 'eyebrow', 'skeptical', 'doubt'],
  '😐': ['neutral', 'blank', 'face', 'meh'],
  '😑': ['expressionless', 'blank', 'face'],
  '😶': ['mouthless', 'silent', 'speechless'],
  '😏': ['smirk', 'smug', 'sly', 'suggestive'],
  '😒': ['unamused', 'disappointed', 'annoyed'],
  '🙄': ['eye', 'roll', 'annoyed', 'whatever'],
  '😬': ['grimace', 'awkward', 'nervous'],
  '🤥': ['lying', 'pinocchio', 'liar', 'nose'],
  '😌': ['relieved', 'content', 'peaceful'],
  '😔': ['pensive', 'sad', 'disappointed'],
  '😪': ['sleepy', 'tired', 'drool'],
  '🤤': ['drool', 'drooling', 'hungry', 'desire'],
  '😴': ['sleep', 'sleeping', 'zzz', 'tired'],
  '😷': ['mask', 'sick', 'ill', 'covid', 'medical'],
  '🤒': ['thermometer', 'sick', 'fever', 'ill'],
  '🤕': ['bandage', 'hurt', 'injured', 'head'],
  '🤢': ['nauseated', 'sick', 'green', 'vomit'],
  '🤮': ['vomit', 'sick', 'puke', 'disgusted'],
  '🤧': ['sneeze', 'sick', 'tissue', 'cold'],
  '🥵': ['hot', 'sweating', 'heat', 'fever'],
  '🥶': ['cold', 'freezing', 'frozen', 'ice'],
  '🥴': ['woozy', 'drunk', 'dizzy', 'tipsy'],
  '😵': ['dizzy', 'dead', 'knocked', 'out'],
  '🤯': ['exploding', 'head', 'mind', 'blown', 'shock'],
  '🤠': ['cowboy', 'hat', 'western', 'yeehaw'],
  '🥳': ['party', 'celebrate', 'birthday', 'fun'],
  '🥸': ['disguise', 'glasses', 'nose', 'incognito'],
  '😎': ['cool', 'sunglasses', 'awesome', 'confident'],
  '🤓': ['nerd', 'geek', 'glasses', 'smart'],
  '🧐': ['monocle', 'curious', 'inspect', 'investigate'],
  '😕': ['confused', 'puzzled', 'unsure'],
  '😟': ['worried', 'concerned', 'anxious'],
  '🙁': ['frowning', 'sad', 'unhappy'],
  '☹️': ['frowning', 'sad', 'unhappy'],
  '😮': ['open', 'mouth', 'surprised', 'wow'],
  '😯': ['hushed', 'surprised', 'speechless'],
  '😲': ['astonished', 'shocked', 'surprised'],
  '😳': ['flushed', 'embarrassed', 'shy', 'blush'],
  '🥺': ['pleading', 'puppy', 'eyes', 'cute', 'please'],
  '😦': ['frowning', 'mouth', 'worried'],
  '😧': ['anguished', 'worried', 'shocked'],
  '😨': ['fearful', 'scared', 'afraid'],
  '😰': ['anxious', 'sweat', 'nervous', 'worried'],
  '😥': ['sad', 'relieved', 'disappointed'],
  '😢': ['crying', 'sad', 'tear', 'upset'],
  '😭': ['sobbing', 'crying', 'sad', 'tears'],
  '😱': ['scream', 'fear', 'scared', 'shock', 'horror'],
  '😖': ['confounded', 'frustrated', 'upset'],
  '😣': ['persevere', 'struggling', 'frustrated'],
  '😞': ['disappointed', 'sad', 'down'],
  '😓': ['downcast', 'sweat', 'tired', 'stressed'],
  '😩': ['weary', 'tired', 'frustrated', 'exhausted'],
  '😫': ['tired', 'exhausted', 'frustrated'],
  '🥱': ['yawn', 'yawning', 'tired', 'bored', 'sleepy'],
  '😤': ['triumph', 'angry', 'frustrated', 'steam'],
  '😡': ['angry', 'mad', 'rage', 'furious'],
  '😠': ['angry', 'mad', 'annoyed'],
  '🤬': ['cursing', 'swearing', 'angry', 'symbols'],
  '😈': ['devil', 'evil', 'mischief', 'horns'],
  '👿': ['angry', 'devil', 'evil', 'demon'],
  '💀': ['skull', 'dead', 'death', 'skeleton'],
  '☠️': ['skull', 'crossbones', 'death', 'danger', 'pirate'],
  '💩': ['poop', 'poo', 'shit', 'crap'],
  '🤡': ['clown', 'circus', 'funny', 'joker'],
  '👹': ['ogre', 'monster', 'demon', 'japanese'],
  '👺': ['goblin', 'tengu', 'monster', 'japanese'],

  // People & Body
  '👋': ['wave', 'hello', 'hi', 'bye', 'hand'],
  '🤚': ['raised', 'back', 'hand', 'stop'],
  '🖐️': ['hand', 'fingers', 'splayed', 'five'],
  '✋': ['hand', 'stop', 'high', 'five'],
  '🖖': ['vulcan', 'spock', 'star', 'trek'],
  '👌': ['ok', 'okay', 'perfect', 'hand'],
  '🤌': ['pinched', 'fingers', 'italian', 'chef'],
  '🤏': ['pinch', 'small', 'tiny', 'little'],
  '✌️': ['peace', 'victory', 'two', 'hand'],
  '🤞': ['crossed', 'fingers', 'luck', 'hope'],
  '🤟': ['love', 'you', 'rock', 'hand'],
  '🤘': ['rock', 'metal', 'horns', 'hand'],
  '🤙': ['call', 'me', 'hang', 'loose', 'shaka'],
  '👈': ['point', 'left', 'hand', 'finger'],
  '👉': ['point', 'right', 'hand', 'finger'],
  '👆': ['point', 'up', 'hand', 'finger'],
  '🖕': ['middle', 'finger', 'rude', 'fuck'],
  '👇': ['point', 'down', 'hand', 'finger'],
  '☝️': ['point', 'up', 'index', 'one'],
  '👍': ['thumbs', 'up', 'like', 'good', 'yes', 'ok'],
  '👎': ['thumbs', 'down', 'dislike', 'bad', 'no'],
  '✊': ['fist', 'punch', 'power', 'raised'],
  '👊': ['fist', 'bump', 'punch'],
  '🤛': ['fist', 'left', 'bump'],
  '🤜': ['fist', 'right', 'bump'],
  '👏': ['clap', 'applause', 'bravo', 'hands'],
  '🙌': ['raised', 'hands', 'celebrate', 'praise'],
  '👐': ['open', 'hands', 'hug'],
  '🤲': ['palms', 'up', 'prayer', 'hands'],
  '🤝': ['handshake', 'deal', 'agreement'],
  '🙏': ['pray', 'please', 'thank', 'namaste', 'hope'],
  '✍️': ['writing', 'hand', 'pen'],
  '💅': ['nail', 'polish', 'manicure', 'beauty'],
  '🤳': ['selfie', 'phone', 'camera'],
  '💪': ['muscle', 'strong', 'arm', 'flex', 'bicep'],
  '🦾': ['mechanical', 'arm', 'robot', 'prosthetic'],
  '🦿': ['mechanical', 'leg', 'robot', 'prosthetic'],
  '🦵': ['leg', 'kick', 'limb'],
  '🦶': ['foot', 'kick', 'stomp'],
  '👂': ['ear', 'listen', 'hear'],
  '🦻': ['ear', 'hearing', 'aid', 'deaf'],
  '👃': ['nose', 'smell', 'sniff'],
  '🧠': ['brain', 'smart', 'think', 'mind'],
  '🫀': ['heart', 'organ', 'anatomical'],
  '🫁': ['lungs', 'breath', 'organ'],
  '🦷': ['tooth', 'dentist', 'teeth'],
  '🦴': ['bone', 'skeleton', 'dog'],
  '👀': ['eyes', 'look', 'see', 'watch'],
  '👁️': ['eye', 'see', 'look', 'watch'],
  '👅': ['tongue', 'lick', 'taste'],
  '👄': ['lips', 'mouth', 'kiss'],
  '👶': ['baby', 'child', 'infant'],
  '🧒': ['child', 'kid', 'young'],
  '👦': ['boy', 'child', 'male', 'kid'],
  '👧': ['girl', 'child', 'female', 'kid'],
  '🧑': ['person', 'adult', 'human'],
  '👱': ['blond', 'blonde', 'hair'],
  '👨': ['man', 'male', 'adult', 'guy'],
  '🧔': ['beard', 'man', 'facial', 'hair'],
  '👩': ['woman', 'female', 'adult', 'lady'],
  '🧓': ['older', 'adult', 'elderly'],
  '👴': ['old', 'man', 'grandpa', 'elderly'],
  '👵': ['old', 'woman', 'grandma', 'elderly'],
  '🙍': ['frowning', 'person', 'unhappy'],
  '🙎': ['pouting', 'person', 'angry'],
  '🙅': ['no', 'gesture', 'crossed', 'arms'],
  '🙆': ['ok', 'gesture', 'arms', 'yes'],
  '💁': ['information', 'desk', 'person', 'help'],
  '🙋': ['raising', 'hand', 'question', 'volunteer'],
  '🧏': ['deaf', 'person', 'hearing'],
  '🙇': ['bow', 'sorry', 'respect', 'apology'],
  '🤦': ['facepalm', 'disappointed', 'frustration'],
  '🤷': ['shrug', 'dunno', 'whatever', 'idk'],
  '👮': ['police', 'cop', 'officer', 'law'],
  '🕵️': ['detective', 'spy', 'sleuth', 'investigate'],
  '💂': ['guard', 'soldier', 'british', 'royal'],
  '🥷': ['ninja', 'stealth', 'warrior', 'hidden'],
  '👷': ['construction', 'worker', 'builder', 'hard', 'hat'],
  '🤴': ['prince', 'royal', 'crown', 'king'],
  '👸': ['princess', 'royal', 'crown', 'queen'],

  // Animals & Nature
  '🐶': ['dog', 'puppy', 'pet', 'cute'],
  '🐱': ['cat', 'kitty', 'pet', 'meow', 'cute'],
  '🐭': ['mouse', 'rat', 'rodent'],
  '🐹': ['hamster', 'pet', 'cute', 'rodent'],
  '🐰': ['rabbit', 'bunny', 'pet', 'cute'],
  '🦊': ['fox', 'animal', 'cunning'],
  '🐻': ['bear', 'animal', 'teddy', 'cute'],
  '🐼': ['panda', 'bear', 'animal', 'cute', 'china'],
  '🐻‍❄️': ['polar', 'bear', 'white', 'arctic'],
  '🐨': ['koala', 'animal', 'australia', 'cute'],
  '🐯': ['tiger', 'cat', 'animal', 'wild'],
  '🦁': ['lion', 'cat', 'animal', 'king', 'wild'],
  '🐮': ['cow', 'animal', 'farm', 'moo'],
  '🐷': ['pig', 'animal', 'farm', 'oink'],
  '🐽': ['pig', 'nose', 'snout'],
  '🐸': ['frog', 'animal', 'toad', 'green'],
  '🐵': ['monkey', 'animal', 'ape', 'primate'],
  '🙈': ['see', 'no', 'evil', 'monkey', 'hide'],
  '🙉': ['hear', 'no', 'evil', 'monkey'],
  '🙊': ['speak', 'no', 'evil', 'monkey'],
  '🐒': ['monkey', 'animal', 'ape', 'primate'],
  '🐔': ['chicken', 'bird', 'farm', 'rooster'],
  '🐧': ['penguin', 'bird', 'animal', 'cold'],
  '🐦': ['bird', 'animal', 'fly'],
  '🐤': ['chick', 'baby', 'bird', 'chicken', 'cute'],
  '🐣': ['hatching', 'chick', 'egg', 'bird'],
  '🐥': ['chick', 'baby', 'bird', 'cute'],
  '🦆': ['duck', 'bird', 'animal', 'quack'],
  '🦅': ['eagle', 'bird', 'america', 'freedom'],
  '🦉': ['owl', 'bird', 'night', 'wise'],
  '🦇': ['bat', 'animal', 'night', 'vampire'],
  '🐺': ['wolf', 'animal', 'howl', 'wild'],
  '🐗': ['boar', 'pig', 'wild', 'animal'],
  '🐴': ['horse', 'animal', 'equine'],
  '🦄': ['unicorn', 'magic', 'horse', 'fantasy'],
  '🐝': ['bee', 'insect', 'honey', 'buzz'],
  '🪱': ['worm', 'insect', 'earth'],
  '🐛': ['bug', 'insect', 'caterpillar'],
  '🦋': ['butterfly', 'insect', 'beautiful', 'nature'],
  '🐌': ['snail', 'slow', 'shell'],
  '🐞': ['ladybug', 'insect', 'beetle', 'lucky'],
  '🐜': ['ant', 'insect', 'bug'],
  '🪰': ['fly', 'insect', 'bug'],
  '🪲': ['beetle', 'insect', 'bug'],
  '🪳': ['cockroach', 'insect', 'bug', 'pest'],
  '🦟': ['mosquito', 'insect', 'bug', 'pest'],
  '🦗': ['cricket', 'insect', 'grasshopper'],
  '🕷️': ['spider', 'insect', 'web', 'scary'],
  '🕸️': ['web', 'spider', 'cobweb'],
  '🦂': ['scorpion', 'insect', 'sting'],
  '🐢': ['turtle', 'animal', 'slow', 'shell'],
  '🐍': ['snake', 'animal', 'reptile'],
  '🦎': ['lizard', 'reptile', 'gecko'],
  '🦖': ['dinosaur', 'trex', 'prehistoric'],
  '🦕': ['dinosaur', 'sauropod', 'prehistoric'],
  '🐙': ['octopus', 'animal', 'sea', 'tentacle'],
  '🦑': ['squid', 'animal', 'sea', 'calamari'],
  '🦐': ['shrimp', 'seafood', 'prawn'],
  '🦞': ['lobster', 'seafood', 'crab'],
  '🦀': ['crab', 'seafood', 'animal'],
  '🐡': ['blowfish', 'fish', 'puffer'],
  '🐠': ['fish', 'tropical', 'aquarium'],
  '🐟': ['fish', 'animal', 'sea'],
  '🐬': ['dolphin', 'animal', 'sea', 'smart'],
  '🐳': ['whale', 'animal', 'sea', 'spouting'],
  '🐋': ['whale', 'animal', 'sea', 'humpback'],
  '🦈': ['shark', 'animal', 'sea', 'dangerous'],
  '🐊': ['crocodile', 'alligator', 'reptile'],
  '🐅': ['tiger', 'animal', 'wild', 'cat'],
  '🐆': ['leopard', 'animal', 'wild', 'cat', 'cheetah'],
  '🦓': ['zebra', 'animal', 'stripes', 'horse'],
  '🦍': ['gorilla', 'ape', 'animal', 'primate'],
  '🦧': ['orangutan', 'ape', 'animal', 'primate'],
  '🦣': ['mammoth', 'elephant', 'prehistoric'],
  '🐘': ['elephant', 'animal', 'big', 'trunk'],
  '🦛': ['hippo', 'hippopotamus', 'animal'],
  '🦏': ['rhino', 'rhinoceros', 'animal', 'horn'],
  '🐪': ['camel', 'animal', 'desert', 'hump'],
  '🐫': ['camel', 'animal', 'desert', 'humps', 'bactrian'],
  '🦒': ['giraffe', 'animal', 'tall', 'neck'],
  '🦘': ['kangaroo', 'animal', 'australia', 'hop'],
  '🦬': ['bison', 'buffalo', 'animal'],
  '🐃': ['water', 'buffalo', 'animal'],
  '🐂': ['ox', 'bull', 'animal'],
  '🐄': ['cow', 'animal', 'farm', 'milk'],
  '🐎': ['horse', 'animal', 'race', 'gallop'],
  '🐖': ['pig', 'animal', 'farm'],
  '🐏': ['ram', 'sheep', 'animal'],
  '🐑': ['sheep', 'animal', 'farm', 'wool'],
  '🦙': ['llama', 'alpaca', 'animal'],
  '🐐': ['goat', 'animal', 'farm'],
  '🦌': ['deer', 'animal', 'buck', 'stag'],
  '🐕': ['dog', 'pet', 'animal'],
  '🐩': ['poodle', 'dog', 'pet', 'fancy'],
  '🦮': ['guide', 'dog', 'service', 'blind'],
  '🐕‍🦺': ['service', 'dog', 'vest'],
  '🐈': ['cat', 'pet', 'animal'],
  '🐈‍⬛': ['black', 'cat', 'pet', 'halloween'],
  '🪶': ['feather', 'bird', 'light', 'quill'],
  '🐓': ['rooster', 'chicken', 'bird', 'farm'],

  // Food & Drink
  '🍇': ['grapes', 'fruit', 'wine', 'purple'],
  '🍈': ['melon', 'fruit', 'green'],
  '🍉': ['watermelon', 'fruit', 'summer', 'red'],
  '🍊': ['orange', 'fruit', 'citrus', 'tangerine'],
  '🍋': ['lemon', 'fruit', 'citrus', 'yellow', 'sour'],
  '🍌': ['banana', 'fruit', 'yellow'],
  '🍍': ['pineapple', 'fruit', 'tropical'],
  '🥭': ['mango', 'fruit', 'tropical'],
  '🍎': ['apple', 'fruit', 'red'],
  '🍏': ['apple', 'fruit', 'green'],
  '🍐': ['pear', 'fruit', 'green'],
  '🍑': ['peach', 'fruit', 'butt', 'emoji'],
  '🍒': ['cherry', 'cherries', 'fruit', 'red'],
  '🍓': ['strawberry', 'fruit', 'berry', 'red'],
  '🫐': ['blueberry', 'fruit', 'berry', 'blue'],
  '🥝': ['kiwi', 'fruit', 'green'],
  '🍅': ['tomato', 'vegetable', 'red', 'food'],
  '🫒': ['olive', 'food', 'green'],
  '🥥': ['coconut', 'fruit', 'tropical'],
  '🥑': ['avocado', 'fruit', 'green', 'guac'],
  '🍆': ['eggplant', 'aubergine', 'vegetable', 'purple'],
  '🥔': ['potato', 'vegetable', 'food'],
  '🥕': ['carrot', 'vegetable', 'orange', 'food'],
  '🌽': ['corn', 'vegetable', 'maize', 'food'],
  '🌶️': ['pepper', 'chili', 'hot', 'spicy'],
  '🫑': ['pepper', 'bell', 'vegetable'],
  '🥒': ['cucumber', 'vegetable', 'pickle'],
  '🥬': ['leafy', 'green', 'vegetable', 'lettuce'],
  '🥦': ['broccoli', 'vegetable', 'green'],
  '🧄': ['garlic', 'vegetable', 'food'],
  '🧅': ['onion', 'vegetable', 'food'],
  '🍄': ['mushroom', 'fungus', 'food'],
  '🥜': ['peanut', 'nut', 'food'],
  '🫘': ['beans', 'food', 'legume'],
  '🌰': ['chestnut', 'nut', 'food'],
  '🍞': ['bread', 'food', 'loaf', 'toast'],
  '🥐': ['croissant', 'bread', 'french', 'pastry'],
  '🥖': ['baguette', 'bread', 'french', 'food'],
  '🫓': ['flatbread', 'pita', 'food'],
  '🥨': ['pretzel', 'snack', 'food', 'german'],
  '🥯': ['bagel', 'bread', 'food'],
  '🥞': ['pancake', 'breakfast', 'food', 'stack'],
  '🧇': ['waffle', 'breakfast', 'food'],
  '🧀': ['cheese', 'food', 'dairy'],
  '🍖': ['meat', 'bone', 'food'],
  '🍗': ['chicken', 'leg', 'meat', 'food', 'drumstick'],
  '🥩': ['steak', 'meat', 'beef', 'food'],
  '🥓': ['bacon', 'meat', 'breakfast', 'food'],
  '🍔': ['burger', 'hamburger', 'food', 'fast'],
  '🍟': ['fries', 'french', 'food', 'fast'],
  '🍕': ['pizza', 'food', 'italian', 'slice'],
  '🌭': ['hotdog', 'food', 'sausage', 'fast'],
  '🥪': ['sandwich', 'food', 'lunch'],
  '🌮': ['taco', 'mexican', 'food'],
  '🌯': ['burrito', 'mexican', 'food', 'wrap'],
  '🫔': ['tamale', 'mexican', 'food'],
  '🥙': ['pita', 'stuffed', 'food', 'falafel'],
  '🧆': ['falafel', 'food', 'middle', 'eastern'],
  '🥚': ['egg', 'food', 'breakfast'],
  '🍳': ['cooking', 'egg', 'fried', 'breakfast', 'pan'],
  '🥘': ['paella', 'pan', 'food', 'cooking'],
  '🍲': ['pot', 'food', 'stew', 'soup'],
  '🫕': ['fondue', 'cheese', 'food'],
  '🥣': ['cereal', 'bowl', 'breakfast', 'food'],
  '🥗': ['salad', 'healthy', 'food', 'green'],
  '🍿': ['popcorn', 'snack', 'movie', 'food'],
  '🧈': ['butter', 'food', 'dairy'],
  '🧂': ['salt', 'seasoning', 'food'],
  '🥫': ['canned', 'food', 'preserve'],
  '🍱': ['bento', 'japanese', 'food', 'box', 'lunch'],
  '🍘': ['rice', 'cracker', 'japanese', 'food'],
  '🍙': ['rice', 'ball', 'onigiri', 'japanese'],
  '🍚': ['rice', 'food', 'japanese', 'bowl'],
  '🍛': ['curry', 'rice', 'food', 'indian'],
  '🍜': ['noodles', 'ramen', 'soup', 'food', 'japanese'],
  '🍝': ['pasta', 'spaghetti', 'italian', 'food'],
  '🍠': ['potato', 'sweet', 'food', 'roasted'],
  '🍢': ['oden', 'japanese', 'food', 'skewer'],
  '🍣': ['sushi', 'japanese', 'food', 'fish'],
  '🍤': ['shrimp', 'tempura', 'fried', 'food'],
  '🍥': ['fish', 'cake', 'narutomaki', 'japanese'],
  '🥮': ['mooncake', 'chinese', 'food'],
  '🍡': ['dango', 'japanese', 'food', 'sweet'],
  '🥟': ['dumpling', 'food', 'chinese', 'asian'],
  '🥠': ['fortune', 'cookie', 'chinese', 'food'],
  '🥡': ['takeout', 'box', 'chinese', 'food'],
  '🦪': ['oyster', 'seafood', 'shellfish'],
  '🍦': ['ice', 'cream', 'cone', 'dessert', 'sweet'],
  '🍧': ['shaved', 'ice', 'dessert', 'cold'],
  '🍨': ['ice', 'cream', 'dessert', 'sweet'],
  '🍩': ['donut', 'doughnut', 'dessert', 'sweet'],
  '🍪': ['cookie', 'dessert', 'sweet', 'biscuit'],
  '🎂': ['birthday', 'cake', 'celebration', 'party'],
  '🍰': ['cake', 'shortcake', 'dessert', 'sweet'],
  '🧁': ['cupcake', 'dessert', 'sweet', 'muffin'],
  '🥧': ['pie', 'dessert', 'sweet', 'food'],
  '🍫': ['chocolate', 'candy', 'sweet', 'bar'],
  '🍬': ['candy', 'sweet', 'wrapper'],
  '🍭': ['lollipop', 'candy', 'sweet'],
  '🍮': ['pudding', 'custard', 'dessert', 'flan'],
  '🍯': ['honey', 'pot', 'sweet', 'bee'],
  '🍼': ['bottle', 'baby', 'milk'],
  '🥛': ['milk', 'glass', 'dairy', 'drink'],
  '☕': ['coffee', 'drink', 'hot', 'cafe', 'tea'],
  '🫖': ['teapot', 'tea', 'drink', 'hot'],
  '🍵': ['tea', 'green', 'drink', 'japanese', 'matcha'],
  '🍶': ['sake', 'japanese', 'drink', 'alcohol'],
  '🍾': ['champagne', 'bottle', 'celebrate', 'wine'],
  '🍷': ['wine', 'glass', 'drink', 'red'],
  '🍸': ['cocktail', 'martini', 'drink', 'alcohol'],
  '🍹': ['tropical', 'drink', 'cocktail'],
  '🍺': ['beer', 'drink', 'mug', 'alcohol'],
  '🍻': ['beer', 'cheers', 'drink', 'mugs'],
  '🥂': ['champagne', 'glasses', 'cheers', 'toast', 'celebrate'],
  '🥃': ['whiskey', 'drink', 'tumbler', 'alcohol'],
  '🥤': ['cup', 'straw', 'drink', 'soda'],

  // Activities
  '⚽': ['soccer', 'football', 'ball', 'sport'],
  '🏀': ['basketball', 'ball', 'sport', 'nba'],
  '🏈': ['football', 'american', 'ball', 'sport', 'nfl'],
  '⚾': ['baseball', 'ball', 'sport'],
  '🥎': ['softball', 'ball', 'sport'],
  '🎾': ['tennis', 'ball', 'sport', 'racket'],
  '🏐': ['volleyball', 'ball', 'sport'],
  '🏉': ['rugby', 'ball', 'sport'],
  '🥏': ['frisbee', 'disc', 'flying'],
  '🎱': ['pool', 'billiard', '8ball', 'eight'],
  '🪀': ['yoyo', 'toy', 'play'],
  '🏓': ['ping', 'pong', 'table', 'tennis'],
  '🏸': ['badminton', 'racket', 'shuttlecock'],
  '🏒': ['hockey', 'ice', 'sport', 'stick'],
  '🏑': ['hockey', 'field', 'sport', 'stick'],
  '🥍': ['lacrosse', 'sport', 'stick'],
  '🏏': ['cricket', 'sport', 'bat', 'ball'],
  '🪃': ['boomerang', 'throw', 'return'],
  '🥅': ['goal', 'net', 'sport'],
  '⛳': ['golf', 'flag', 'sport', 'hole'],
  '🪁': ['kite', 'fly', 'wind', 'toy'],
  '🏹': ['bow', 'arrow', 'archery'],
  '🎣': ['fishing', 'rod', 'fish', 'pole'],
  '🤿': ['diving', 'mask', 'snorkel', 'scuba'],
  '🥊': ['boxing', 'glove', 'sport', 'fight'],
  '🥋': ['martial', 'arts', 'karate', 'judo'],
  '🎽': ['running', 'shirt', 'sport', 'marathon'],
  '🛹': ['skateboard', 'skate', 'sport'],
  '🛼': ['roller', 'skate', 'skating'],
  '🛷': ['sled', 'sledge', 'snow', 'winter'],
  '⛸️': ['ice', 'skate', 'skating', 'winter'],
  '🥌': ['curling', 'stone', 'sport', 'winter'],
  '🎿': ['ski', 'skiing', 'snow', 'winter', 'sport'],
  '⛷️': ['skier', 'skiing', 'snow', 'winter'],
  '🏂': ['snowboard', 'snow', 'winter', 'sport'],
  '🪂': ['parachute', 'skydiving', 'falling'],
  '🏋️': ['weightlifting', 'gym', 'fitness', 'strong'],
  '🤼': ['wrestling', 'sport', 'fight'],
  '🤸': ['cartwheel', 'gymnastics', 'acrobat'],
  '🤺': ['fencing', 'sword', 'sport'],
  '⛹️': ['basketball', 'player', 'sport', 'ball'],
  '🤾': ['handball', 'sport', 'player'],
  '🏌️': ['golf', 'golfer', 'sport'],
  '🏇': ['horse', 'racing', 'jockey', 'sport'],
  '🧘': ['yoga', 'meditation', 'zen', 'lotus'],
  '🏄': ['surfing', 'surf', 'wave', 'beach'],
  '🏊': ['swimming', 'swim', 'pool', 'water'],
  '🤽': ['water', 'polo', 'sport', 'swim'],
  '🚣': ['rowing', 'boat', 'canoe', 'paddle'],
  '🧗': ['climbing', 'rock', 'sport', 'mountain'],
  '🚵': ['mountain', 'bike', 'cycling', 'biking'],
  '🚴': ['cycling', 'bike', 'bicycle', 'biking'],
  '🏆': ['trophy', 'winner', 'champion', 'award', 'gold'],
  '🥇': ['gold', 'medal', 'first', 'winner', '1st'],
  '🥈': ['silver', 'medal', 'second', '2nd'],
  '🥉': ['bronze', 'medal', 'third', '3rd'],
  '🏅': ['medal', 'sports', 'award'],
  '🎖️': ['military', 'medal', 'honor'],
  '🏵️': ['rosette', 'flower', 'award'],
  '🎗️': ['ribbon', 'awareness', 'reminder'],
  '🎫': ['ticket', 'admission', 'event'],
  '🎟️': ['ticket', 'admission', 'event', 'entry'],
  '🎪': ['circus', 'tent', 'show'],
  '🤹': ['juggling', 'circus', 'perform'],
  '🎭': ['theater', 'drama', 'masks', 'performing', 'arts'],
  '🩰': ['ballet', 'dance', 'shoes'],
  '🎨': ['art', 'paint', 'palette', 'artist', 'creative'],
  '🎬': ['movie', 'film', 'cinema', 'clapper', 'action'],
  '🎤': ['microphone', 'mic', 'sing', 'karaoke', 'music'],
  '🎧': ['headphones', 'music', 'audio', 'listen'],
  '🎼': ['music', 'score', 'notes', 'sheet'],
  '🎹': ['piano', 'keyboard', 'music', 'instrument'],
  '🥁': ['drum', 'drums', 'music', 'percussion'],
  '🪘': ['drum', 'percussion', 'music', 'long'],
  '🎷': ['saxophone', 'sax', 'music', 'jazz'],
  '🎺': ['trumpet', 'music', 'brass', 'horn'],
  '🪗': ['accordion', 'music', 'instrument'],
  '🎸': ['guitar', 'music', 'rock', 'instrument'],
  '🪕': ['banjo', 'music', 'country', 'instrument'],
  '🎻': ['violin', 'music', 'fiddle', 'classical'],
  '🎲': ['dice', 'game', 'gambling', 'random'],
  '♟️': ['chess', 'pawn', 'game', 'strategy'],
  '🎯': ['target', 'dart', 'bullseye', 'goal'],
  '🎳': ['bowling', 'ball', 'pins', 'sport'],
  '🎮': ['game', 'controller', 'video', 'gaming', 'play'],
  '🎰': ['slot', 'machine', 'casino', 'gambling'],
  '🧩': ['puzzle', 'piece', 'jigsaw', 'game'],

  // Objects
  '⌚': ['watch', 'time', 'clock', 'wrist'],
  '📱': ['phone', 'mobile', 'iphone', 'smartphone', 'cell'],
  '📲': ['phone', 'mobile', 'arrow', 'call'],
  '💻': ['laptop', 'computer', 'macbook', 'pc'],
  '⌨️': ['keyboard', 'computer', 'type', 'input'],
  '🖥️': ['desktop', 'computer', 'monitor', 'screen'],
  '🖨️': ['printer', 'print', 'paper'],
  '🖱️': ['mouse', 'computer', 'click'],
  '🖲️': ['trackball', 'computer', 'input'],
  '🕹️': ['joystick', 'game', 'controller', 'arcade'],
  '🗜️': ['clamp', 'compress', 'tool'],
  '💽': ['disc', 'minidisc', 'computer', 'storage'],
  '💾': ['floppy', 'disk', 'save', 'storage'],
  '💿': ['cd', 'disc', 'dvd', 'music'],
  '📀': ['dvd', 'disc', 'movie', 'video'],
  '📼': ['vhs', 'tape', 'video', 'cassette'],
  '📷': ['camera', 'photo', 'picture'],
  '📸': ['camera', 'flash', 'photo', 'picture'],
  '📹': ['video', 'camera', 'camcorder', 'record'],
  '🎥': ['movie', 'camera', 'film', 'cinema'],
  '📽️': ['projector', 'film', 'movie'],
  '🎞️': ['film', 'frames', 'movie', 'cinema'],
  '📞': ['telephone', 'phone', 'receiver', 'call'],
  '☎️': ['telephone', 'phone', 'landline', 'call'],
  '📟': ['pager', 'beeper'],
  '📠': ['fax', 'machine', 'office'],
  '📺': ['television', 'tv', 'screen', 'watch'],
  '📻': ['radio', 'music', 'audio'],
  '🎙️': ['microphone', 'studio', 'podcast', 'recording'],
  '🎚️': ['slider', 'level', 'audio', 'volume'],
  '🎛️': ['knobs', 'control', 'dials', 'audio'],
  '🧭': ['compass', 'navigation', 'direction'],
  '⏱️': ['stopwatch', 'timer', 'time'],
  '⏲️': ['timer', 'clock', 'time'],
  '⏰': ['alarm', 'clock', 'time', 'wake'],
  '🕰️': ['clock', 'mantelpiece', 'time'],
  '⌛': ['hourglass', 'time', 'sand', 'wait'],
  '⏳': ['hourglass', 'time', 'sand', 'flowing'],
  '📡': ['satellite', 'antenna', 'dish', 'signal'],
  '🔋': ['battery', 'power', 'charge', 'energy'],
  '🔌': ['plug', 'electric', 'power', 'outlet'],
  '💡': ['lightbulb', 'idea', 'light', 'bright'],
  '🔦': ['flashlight', 'torch', 'light'],
  '🕯️': ['candle', 'light', 'flame'],
  '🪔': ['lamp', 'diya', 'oil', 'light'],
  '🧯': ['fire', 'extinguisher', 'safety'],
  '🛢️': ['oil', 'drum', 'barrel'],
  '💸': ['money', 'flying', 'cash', 'dollar'],
  '💵': ['dollar', 'money', 'cash', 'bill'],
  '💴': ['yen', 'money', 'cash', 'japanese'],
  '💶': ['euro', 'money', 'cash'],
  '💷': ['pound', 'money', 'cash', 'british'],
  '🪙': ['coin', 'money', 'gold'],
  '💰': ['money', 'bag', 'rich', 'dollar'],
  '💳': ['credit', 'card', 'payment', 'bank'],
  '💎': ['diamond', 'gem', 'jewel', 'precious'],
  '⚖️': ['scale', 'balance', 'justice', 'law'],
  '🪜': ['ladder', 'climb', 'steps'],
  '🧰': ['toolbox', 'tools', 'repair'],
  '🪛': ['screwdriver', 'tool', 'repair'],
  '🔧': ['wrench', 'tool', 'repair', 'fix'],
  '🔨': ['hammer', 'tool', 'build', 'construction'],
  '⚒️': ['hammer', 'pick', 'tool', 'mining'],
  '🛠️': ['tools', 'hammer', 'wrench', 'repair'],
  '⛏️': ['pick', 'mining', 'tool'],
  '🪚': ['saw', 'carpentry', 'tool', 'wood'],
  '🔩': ['nut', 'bolt', 'screw', 'tool'],
  '⚙️': ['gear', 'cog', 'settings', 'mechanical'],
  '🪤': ['mouse', 'trap'],
  '🧱': ['brick', 'wall', 'building', 'construction'],
  '⛓️': ['chain', 'link', 'metal'],
  '🧲': ['magnet', 'attraction', 'magnetic'],
  '🔫': ['gun', 'pistol', 'water', 'weapon'],
  '💣': ['bomb', 'explosion', 'danger'],
  '🧨': ['firecracker', 'dynamite', 'explosion'],
  '🪓': ['axe', 'chop', 'wood', 'tool'],
  '🔪': ['knife', 'kitchen', 'cut', 'blade'],
  '🗡️': ['dagger', 'sword', 'knife', 'weapon'],
  '⚔️': ['swords', 'crossed', 'battle', 'fight'],
  '🛡️': ['shield', 'protect', 'defense'],
  '🚬': ['cigarette', 'smoking', 'tobacco'],
  '⚰️': ['coffin', 'death', 'funeral'],
  '🪦': ['headstone', 'grave', 'cemetery', 'rip'],
  '⚱️': ['urn', 'funeral', 'ashes'],
  '🏺': ['amphora', 'jar', 'vase'],
  '🔮': ['crystal', 'ball', 'fortune', 'magic'],
  '📿': ['prayer', 'beads', 'necklace'],
  '🧿': ['nazar', 'evil', 'eye', 'amulet'],
  '💈': ['barber', 'pole', 'haircut'],
  '⚗️': ['alembic', 'chemistry', 'science'],
  '🔭': ['telescope', 'astronomy', 'stars', 'space'],
  '🔬': ['microscope', 'science', 'research', 'biology'],
  '🕳️': ['hole', 'black', 'void'],
  '🩹': ['bandage', 'adhesive', 'heal', 'medical'],
  '🩺': ['stethoscope', 'doctor', 'medical', 'health'],
  '💊': ['pill', 'medicine', 'drug', 'health'],
  '💉': ['syringe', 'injection', 'vaccine', 'medical'],
  '🩸': ['blood', 'drop', 'donate', 'medical'],
  '🧬': ['dna', 'gene', 'genetics', 'science'],
  '🦠': ['microbe', 'virus', 'bacteria', 'germ'],

  // Symbols
  '❤️': ['heart', 'love', 'red', 'like'],
  '🧡': ['heart', 'orange', 'love'],
  '💛': ['heart', 'yellow', 'love'],
  '💚': ['heart', 'green', 'love'],
  '💙': ['heart', 'blue', 'love'],
  '💜': ['heart', 'purple', 'love'],
  '🖤': ['heart', 'black', 'love', 'dark'],
  '🤍': ['heart', 'white', 'love'],
  '🤎': ['heart', 'brown', 'love'],
  '💔': ['broken', 'heart', 'sad', 'love'],
  '❣️': ['heart', 'exclamation', 'love'],
  '💕': ['hearts', 'two', 'love'],
  '💞': ['hearts', 'revolving', 'love'],
  '💓': ['heart', 'beating', 'love'],
  '💗': ['heart', 'growing', 'love'],
  '💖': ['heart', 'sparkle', 'love'],
  '💘': ['heart', 'arrow', 'cupid', 'love'],
  '💝': ['heart', 'ribbon', 'gift', 'love'],
  '💟': ['heart', 'decoration', 'love'],
  '☮️': ['peace', 'symbol', 'hippie'],
  '✝️': ['cross', 'christian', 'religion'],
  '☪️': ['star', 'crescent', 'islam', 'muslim'],
  '🕉️': ['om', 'hindu', 'religion'],
  '☸️': ['wheel', 'dharma', 'buddhism'],
  '✡️': ['star', 'david', 'jewish', 'judaism'],
  '🔯': ['star', 'six', 'pointed'],
  '🕎': ['menorah', 'jewish', 'candles', 'hanukkah'],
  '☯️': ['yin', 'yang', 'balance', 'tao'],
  '☦️': ['orthodox', 'cross', 'religion'],
  '🛐': ['worship', 'place', 'religion'],
  '⛎': ['ophiuchus', 'zodiac'],
  '♈': ['aries', 'zodiac', 'horoscope'],
  '♉': ['taurus', 'zodiac', 'horoscope'],
  '♊': ['gemini', 'zodiac', 'horoscope'],
  '♋': ['cancer', 'zodiac', 'horoscope'],
  '♌': ['leo', 'zodiac', 'horoscope'],
  '♍': ['virgo', 'zodiac', 'horoscope'],
  '♎': ['libra', 'zodiac', 'horoscope'],
  '♏': ['scorpio', 'zodiac', 'horoscope'],
  '♐': ['sagittarius', 'zodiac', 'horoscope'],
  '♑': ['capricorn', 'zodiac', 'horoscope'],
  '♒': ['aquarius', 'zodiac', 'horoscope'],
  '♓': ['pisces', 'zodiac', 'horoscope'],
  '🆔': ['id', 'identity', 'identification'],
  '⚛️': ['atom', 'science', 'physics', 'nuclear'],
  '🉑': ['accept', 'chinese', 'kanji'],
  '☢️': ['radioactive', 'nuclear', 'radiation', 'danger'],
  '☣️': ['biohazard', 'danger', 'warning'],
  '📴': ['phone', 'off', 'mobile', 'silent'],
  '📳': ['vibration', 'phone', 'mode'],
  '🈶': ['have', 'chinese', 'kanji'],
  '🈚': ['nothing', 'chinese', 'kanji', 'free'],
  '🈸': ['apply', 'chinese', 'kanji'],
  '🈺': ['open', 'chinese', 'kanji', 'business'],
  '🈷️': ['month', 'chinese', 'kanji'],
  '✴️': ['star', 'eight', 'pointed'],
  '🆚': ['vs', 'versus', 'against'],
  '💮': ['flower', 'white', 'good'],
  '🉐': ['bargain', 'chinese', 'kanji', 'discount'],
  '㊙️': ['secret', 'chinese', 'kanji'],
  '㊗️': ['congratulations', 'chinese', 'kanji'],
  '🈴': ['passing', 'chinese', 'kanji', 'score'],
  '🈵': ['full', 'chinese', 'kanji', 'no', 'vacancy'],
  '🈹': ['discount', 'chinese', 'kanji', 'sale'],
  '🈲': ['prohibited', 'chinese', 'kanji', 'forbidden'],
  '🅰️': ['a', 'blood', 'type', 'letter'],
  '🅱️': ['b', 'blood', 'type', 'letter'],
  '🆎': ['ab', 'blood', 'type'],
  '🆑': ['cl', 'clear'],
  '🅾️': ['o', 'blood', 'type', 'letter'],
  '🆘': ['sos', 'help', 'emergency'],
  '❌': ['x', 'cross', 'no', 'wrong', 'delete'],
  '⭕': ['circle', 'o', 'ring'],
  '🛑': ['stop', 'sign', 'octagon'],
  '⛔': ['no', 'entry', 'forbidden', 'stop'],
  '📛': ['name', 'badge', 'tag'],
  '🚫': ['prohibited', 'no', 'forbidden', 'ban'],
  '💯': ['hundred', '100', 'perfect', 'score'],
  '💢': ['anger', 'symbol', 'mad'],
  '♨️': ['hot', 'springs', 'steam'],
  '🚷': ['no', 'pedestrians', 'walking'],
  '🚯': ['no', 'littering', 'trash'],
  '🚳': ['no', 'bicycles', 'bikes'],
  '🚱': ['no', 'drinking', 'water'],
  '🔞': ['18', 'adult', 'only', 'nsfw'],
  '📵': ['no', 'mobile', 'phones'],
  '🚭': ['no', 'smoking'],
  '❗': ['exclamation', 'mark', 'warning', 'alert'],
  '❕': ['exclamation', 'white', 'mark'],
  '❓': ['question', 'mark', 'confused'],
  '❔': ['question', 'white', 'mark'],
  '‼️': ['double', 'exclamation', 'mark'],
  '⁉️': ['exclamation', 'question', 'mark'],
  '🔅': ['dim', 'brightness', 'low'],
  '🔆': ['bright', 'brightness', 'high'],
  '〽️': ['part', 'alternation', 'mark'],
  '⚠️': ['warning', 'caution', 'alert', 'danger'],
  '🚸': ['children', 'crossing', 'sign'],
  '🔱': ['trident', 'emblem', 'poseidon'],
  '⚜️': ['fleur', 'de', 'lis', 'scout'],
  '🔰': ['beginner', 'japanese', 'symbol'],
  '♻️': ['recycle', 'recycling', 'green', 'environment'],
  '✅': ['check', 'mark', 'yes', 'correct', 'done', 'complete'],
  '🈯': ['reserved', 'chinese', 'kanji'],
  '💹': ['chart', 'increasing', 'yen', 'stock'],
  '❇️': ['sparkle', 'star'],
  '✳️': ['asterisk', 'star', 'eight'],
  '❎': ['x', 'mark', 'cross', 'no'],
  '🌐': ['globe', 'web', 'internet', 'world'],
  '💠': ['diamond', 'cute', 'kawaii'],
  'Ⓜ️': ['m', 'metro', 'circle'],
  '🌀': ['cyclone', 'spiral', 'typhoon', 'hurricane'],
  '💤': ['zzz', 'sleep', 'sleepy', 'tired'],
  '🏧': ['atm', 'bank', 'money'],
  '🚾': ['wc', 'toilet', 'restroom', 'bathroom'],
  '♿': ['wheelchair', 'accessible', 'disability'],
  '🅿️': ['parking', 'p', 'car'],
  '🛗': ['elevator', 'lift'],
  '🈳': ['vacancy', 'chinese', 'kanji', 'empty'],
  '🈂️': ['service', 'charge', 'chinese'],
  '🛂': ['passport', 'control', 'customs'],
  '🛃': ['customs', 'border'],
  '🛄': ['baggage', 'claim', 'luggage'],
  '🛅': ['left', 'luggage', 'locker'],
  '🚹': ['mens', 'bathroom', 'toilet', 'male'],
  '🚺': ['womens', 'bathroom', 'toilet', 'female'],
  '🚼': ['baby', 'symbol', 'changing'],
  '⚧️': ['transgender', 'symbol', 'gender'],
  '🚻': ['restroom', 'toilet', 'bathroom', 'wc'],
  '🚮': ['litter', 'bin', 'trash'],
  '🎦': ['cinema', 'movie', 'film'],
  '📶': ['signal', 'bars', 'mobile', 'wifi'],
  '🈁': ['here', 'japanese', 'katakana'],
  '🔣': ['symbols', 'input'],
  'ℹ️': ['information', 'info', 'source'],
  '🔤': ['abc', 'alphabet', 'letters'],
  '🔡': ['lowercase', 'abcd', 'letters'],
  '🔠': ['uppercase', 'abcd', 'letters'],
  '🆖': ['ng', 'no', 'good'],
  '🆗': ['ok', 'button', 'good'],
  '🆙': ['up', 'button', 'new'],
  '🆒': ['cool', 'button'],
  '🆕': ['new', 'button'],
  '🆓': ['free', 'button', 'gratis'],
  '0️⃣': ['zero', '0', 'number'],
  '1️⃣': ['one', '1', 'number'],
  '2️⃣': ['two', '2', 'number'],
  '3️⃣': ['three', '3', 'number'],
  '4️⃣': ['four', '4', 'number'],
  '5️⃣': ['five', '5', 'number'],
  '6️⃣': ['six', '6', 'number'],
  '7️⃣': ['seven', '7', 'number'],
  '8️⃣': ['eight', '8', 'number'],
  '9️⃣': ['nine', '9', 'number'],
  '🔟': ['ten', '10', 'number'],
  '🔢': ['numbers', '1234', 'input'],
  '#️⃣': ['hash', 'hashtag', 'number', 'pound'],
  '*️⃣': ['asterisk', 'star', 'keycap'],
  '⏏️': ['eject', 'button'],
  '▶️': ['play', 'button', 'start'],
  '⏸️': ['pause', 'button'],
  '⏯️': ['play', 'pause', 'button'],
  '⏹️': ['stop', 'button'],
  '⏺️': ['record', 'button'],
  '⏭️': ['next', 'track', 'skip'],
  '⏮️': ['previous', 'track', 'back'],
  '⏩': ['fast', 'forward'],
  '⏪': ['rewind', 'back'],
  '⏫': ['up', 'arrow', 'fast'],
  '⏬': ['down', 'arrow', 'fast'],
  '◀️': ['reverse', 'button', 'back'],
  '🔼': ['up', 'button', 'arrow'],
  '🔽': ['down', 'button', 'arrow'],
  '➡️': ['right', 'arrow'],
  '⬅️': ['left', 'arrow'],
  '⬆️': ['up', 'arrow'],
  '⬇️': ['down', 'arrow'],
  '↗️': ['up', 'right', 'arrow', 'northeast'],
  '↘️': ['down', 'right', 'arrow', 'southeast'],
  '↙️': ['down', 'left', 'arrow', 'southwest'],
  '↖️': ['up', 'left', 'arrow', 'northwest'],
  '↕️': ['up', 'down', 'arrow'],
  '↔️': ['left', 'right', 'arrow'],
  '↪️': ['right', 'arrow', 'curving'],
  '↩️': ['left', 'arrow', 'curving'],
  '⤴️': ['up', 'arrow', 'curving', 'right'],
  '⤵️': ['down', 'arrow', 'curving', 'right'],
  '🔀': ['shuffle', 'random', 'twisted', 'arrows'],
  '🔁': ['repeat', 'loop', 'arrows'],
  '🔂': ['repeat', 'single', 'one'],
  '🔄': ['refresh', 'reload', 'sync', 'arrows'],
  '🔃': ['clockwise', 'arrows', 'reload'],
  '🎵': ['music', 'note', 'song'],
  '🎶': ['music', 'notes', 'song', 'melody'],
  '➕': ['plus', 'add', 'math'],
  '➖': ['minus', 'subtract', 'math'],
  '➗': ['divide', 'division', 'math'],
  '✖️': ['multiply', 'x', 'math'],
  '🟰': ['equal', 'equals', 'math'],
  '♾️': ['infinity', 'forever', 'unlimited'],
  '💲': ['dollar', 'money', 'sign'],
  '💱': ['currency', 'exchange', 'money'],
  '™️': ['trademark', 'tm', 'brand'],
  '©️': ['copyright', 'c'],
  '®️': ['registered', 'r', 'trademark'],
  '〰️': ['wavy', 'dash', 'line'],
  '➰': ['curly', 'loop'],
  '➿': ['double', 'curly', 'loop'],
  '🔚': ['end', 'arrow'],
  '🔙': ['back', 'arrow'],
  '🔛': ['on', 'arrow', 'mark'],
  '🔝': ['top', 'arrow'],
  '🔜': ['soon', 'arrow'],
  '✔️': ['check', 'mark', 'yes', 'correct'],
  '☑️': ['check', 'box', 'ballot'],
  '🔘': ['radio', 'button'],
  '🔴': ['red', 'circle'],
  '🟠': ['orange', 'circle'],
  '🟡': ['yellow', 'circle'],
  '🟢': ['green', 'circle'],
  '🔵': ['blue', 'circle'],
  '🟣': ['purple', 'circle'],
  '⚫': ['black', 'circle'],
  '⚪': ['white', 'circle'],
  '🟤': ['brown', 'circle'],
  '🔺': ['red', 'triangle', 'up'],
  '🔻': ['red', 'triangle', 'down'],
  '🔸': ['orange', 'diamond', 'small'],
  '🔹': ['blue', 'diamond', 'small'],
  '🔶': ['orange', 'diamond', 'large'],
  '🔷': ['blue', 'diamond', 'large'],
  '🔳': ['white', 'square', 'button'],
  '🔲': ['black', 'square', 'button'],
  '▪️': ['black', 'square', 'small'],
  '▫️': ['white', 'square', 'small'],
  '◾': ['black', 'square', 'medium', 'small'],
  '◽': ['white', 'square', 'medium', 'small'],
  '◼️': ['black', 'square', 'medium'],
  '◻️': ['white', 'square', 'medium'],
  '🟥': ['red', 'square'],
  '🟧': ['orange', 'square'],
  '🟨': ['yellow', 'square'],
  '🟩': ['green', 'square'],
  '🟦': ['blue', 'square'],
  '🟪': ['purple', 'square'],
  '⬛': ['black', 'square', 'large'],
  '⬜': ['white', 'square', 'large'],
  '🟫': ['brown', 'square'],
  '🔈': ['speaker', 'low', 'volume'],
  '🔇': ['mute', 'speaker', 'silent'],
  '🔉': ['speaker', 'medium', 'volume'],
  '🔊': ['speaker', 'loud', 'volume', 'sound'],
  '🔔': ['bell', 'notification', 'alert'],
  '🔕': ['bell', 'silent', 'mute', 'no'],
  '📣': ['megaphone', 'cheering', 'announcement'],
  '📢': ['loudspeaker', 'announcement', 'public'],
  '👁️‍🗨️': ['eye', 'speech', 'bubble', 'witness'],
  '💬': ['speech', 'bubble', 'comment', 'message', 'chat'],
  '💭': ['thought', 'bubble', 'thinking'],
  '🗯️': ['anger', 'bubble', 'right'],
  '♠️': ['spade', 'card', 'suit', 'poker'],
  '♣️': ['club', 'card', 'suit', 'poker'],
  '♥️': ['heart', 'card', 'suit', 'poker'],
  '♦️': ['diamond', 'card', 'suit', 'poker'],
  '🃏': ['joker', 'card', 'wild'],
  '🎴': ['flower', 'playing', 'cards', 'hanafuda'],
  '🀄': ['mahjong', 'red', 'dragon', 'tile'],
  '🕐': ['one', 'clock', '1:00', 'time'],
  '🕑': ['two', 'clock', '2:00', 'time'],
  '🕒': ['three', 'clock', '3:00', 'time'],
  '🕓': ['four', 'clock', '4:00', 'time'],
  '🕔': ['five', 'clock', '5:00', 'time'],
  '🕕': ['six', 'clock', '6:00', 'time'],
  '🕖': ['seven', 'clock', '7:00', 'time'],
  '🕗': ['eight', 'clock', '8:00', 'time'],
  '🕘': ['nine', 'clock', '9:00', 'time'],
  '🕙': ['ten', 'clock', '10:00', 'time'],
  '🕚': ['eleven', 'clock', '11:00', 'time'],
  '🕛': ['twelve', 'clock', '12:00', 'noon', 'time'],
  '🕜': ['one', 'thirty', '1:30', 'time'],
  '🕝': ['two', 'thirty', '2:30', 'time'],
  '🕞': ['three', 'thirty', '3:30', 'time'],
  '🕟': ['four', 'thirty', '4:30', 'time'],
  '🕠': ['five', 'thirty', '5:30', 'time'],
  '🕡': ['six', 'thirty', '6:30', 'time'],
  '🕢': ['seven', 'thirty', '7:30', 'time'],
  '🕣': ['eight', 'thirty', '8:30', 'time'],
  '🕤': ['nine', 'thirty', '9:30', 'time'],
  '🕥': ['ten', 'thirty', '10:30', 'time'],
  '🕦': ['eleven', 'thirty', '11:30', 'time'],
  '🕧': ['twelve', 'thirty', '12:30', 'time'],

  // Flags
  '🏳️': ['white', 'flag', 'surrender'],
  '🏴': ['black', 'flag', 'pirate'],
  '🏴‍☠️': ['pirate', 'flag', 'skull', 'crossbones'],
  '🏁': ['checkered', 'flag', 'race', 'finish'],
  '🚩': ['red', 'flag', 'triangular', 'warning'],
  '🎌': ['crossed', 'flags', 'japan', 'celebration'],
  '🏳️‍🌈': ['rainbow', 'flag', 'pride', 'lgbtq', 'gay'],
  '🏳️‍⚧️': ['transgender', 'flag', 'pride', 'trans'],
  '🇺🇳': ['united', 'nations', 'un', 'flag'],
  '🇦🇫': ['afghanistan', 'flag', 'af'],
  '🇦🇽': ['aland', 'islands', 'flag'],
  '🇦🇱': ['albania', 'flag', 'al'],
  '🇩🇿': ['algeria', 'flag', 'dz'],
  '🇦🇸': ['american', 'samoa', 'flag'],
  '🇦🇩': ['andorra', 'flag', 'ad'],
  '🇦🇴': ['angola', 'flag', 'ao'],
  '🇦🇮': ['anguilla', 'flag'],
  '🇦🇶': ['antarctica', 'flag'],
  '🇦🇬': ['antigua', 'barbuda', 'flag'],
  '🇦🇷': ['argentina', 'flag', 'ar'],
  '🇦🇲': ['armenia', 'flag', 'am'],
  '🇦🇼': ['aruba', 'flag'],
  '🇦🇺': ['australia', 'flag', 'au', 'aussie'],
  '🇦🇹': ['austria', 'flag', 'at'],
  '🇦🇿': ['azerbaijan', 'flag', 'az'],
  '🇧🇸': ['bahamas', 'flag', 'bs'],
  '🇧🇭': ['bahrain', 'flag', 'bh'],
  '🇧🇩': ['bangladesh', 'flag', 'bd'],
  '🇧🇧': ['barbados', 'flag', 'bb'],
  '🇧🇾': ['belarus', 'flag', 'by'],
  '🇧🇪': ['belgium', 'flag', 'be'],
  '🇧🇿': ['belize', 'flag', 'bz'],
  '🇧🇯': ['benin', 'flag', 'bj'],
  '🇧🇲': ['bermuda', 'flag'],
  '🇧🇹': ['bhutan', 'flag', 'bt'],
  '🇧🇴': ['bolivia', 'flag', 'bo'],
  '🇧🇦': ['bosnia', 'herzegovina', 'flag', 'ba'],
  '🇧🇼': ['botswana', 'flag', 'bw'],
  '🇧🇷': ['brazil', 'flag', 'br', 'brasil'],
  '🇧🇳': ['brunei', 'flag', 'bn'],
  '🇧🇬': ['bulgaria', 'flag', 'bg'],
  '🇧🇫': ['burkina', 'faso', 'flag', 'bf'],
  '🇧🇮': ['burundi', 'flag', 'bi'],
  '🇰🇭': ['cambodia', 'flag', 'kh'],
  '🇨🇲': ['cameroon', 'flag', 'cm'],
  '🇨🇦': ['canada', 'flag', 'ca', 'maple'],
  '🇨🇻': ['cape', 'verde', 'flag', 'cv'],
  '🇨🇫': ['central', 'african', 'republic', 'flag', 'cf'],
  '🇹🇩': ['chad', 'flag', 'td'],
  '🇨🇱': ['chile', 'flag', 'cl'],
  '🇨🇳': ['china', 'flag', 'cn', 'chinese', 'prc'],
  '🇨🇴': ['colombia', 'flag', 'co'],
  '🇰🇲': ['comoros', 'flag', 'km'],
  '🇨🇬': ['congo', 'flag', 'cg', 'brazzaville'],
  '🇨🇩': ['congo', 'drc', 'flag', 'cd', 'kinshasa'],
  '🇨🇷': ['costa', 'rica', 'flag', 'cr'],
  '🇨🇮': ['cote', 'divoire', 'ivory', 'coast', 'flag', 'ci'],
  '🇭🇷': ['croatia', 'flag', 'hr'],
  '🇨🇺': ['cuba', 'flag', 'cu'],
  '🇨🇼': ['curacao', 'flag', 'cw'],
  '🇨🇾': ['cyprus', 'flag', 'cy'],
  '🇨🇿': ['czech', 'republic', 'czechia', 'flag', 'cz'],
  '🇩🇰': ['denmark', 'flag', 'dk'],
  '🇩🇯': ['djibouti', 'flag', 'dj'],
  '🇩🇲': ['dominica', 'flag', 'dm'],
  '🇩🇴': ['dominican', 'republic', 'flag', 'do'],
  '🇪🇨': ['ecuador', 'flag', 'ec'],
  '🇪🇬': ['egypt', 'flag', 'eg'],
  '🇸🇻': ['el', 'salvador', 'flag', 'sv'],
  '🇬🇶': ['equatorial', 'guinea', 'flag', 'gq'],
  '🇪🇷': ['eritrea', 'flag', 'er'],
  '🇪🇪': ['estonia', 'flag', 'ee'],
  '🇸🇿': ['eswatini', 'swaziland', 'flag', 'sz'],
  '🇪🇹': ['ethiopia', 'flag', 'et'],
  '🇫🇯': ['fiji', 'flag', 'fj'],
  '🇫🇮': ['finland', 'flag', 'fi'],
  '🇫🇷': ['france', 'flag', 'fr', 'french'],
  '🇬🇦': ['gabon', 'flag', 'ga'],
  '🇬🇲': ['gambia', 'flag', 'gm'],
  '🇬🇪': ['georgia', 'flag', 'ge'],
  '🇩🇪': ['germany', 'flag', 'de', 'german', 'deutschland'],
  '🇬🇭': ['ghana', 'flag', 'gh'],
  '🇬🇷': ['greece', 'flag', 'gr', 'greek'],
  '🇬🇹': ['guatemala', 'flag', 'gt'],
  '🇬🇳': ['guinea', 'flag', 'gn'],
  '🇬🇾': ['guyana', 'flag', 'gy'],
  '🇭🇹': ['haiti', 'flag', 'ht'],
  '🇭🇳': ['honduras', 'flag', 'hn'],
  '🇭🇰': ['hong', 'kong', 'flag', 'hk'],
  '🇭🇺': ['hungary', 'flag', 'hu'],
  '🇮🇸': ['iceland', 'flag', 'is'],
  '🇮🇳': ['india', 'flag', 'in', 'indian'],
  '🇮🇩': ['indonesia', 'flag', 'id'],
  '🇮🇷': ['iran', 'flag', 'ir'],
  '🇮🇶': ['iraq', 'flag', 'iq'],
  '🇮🇪': ['ireland', 'flag', 'ie', 'irish'],
  '🇮🇱': ['israel', 'flag', 'il'],
  '🇮🇹': ['italy', 'flag', 'it', 'italian'],
  '🇯🇲': ['jamaica', 'flag', 'jm'],
  '🇯🇵': ['japan', 'flag', 'jp', 'japanese'],
  '🇯🇴': ['jordan', 'flag', 'jo'],
  '🇰🇿': ['kazakhstan', 'flag', 'kz'],
  '🇰🇪': ['kenya', 'flag', 'ke'],
  '🇰🇮': ['kiribati', 'flag', 'ki'],
  '🇽🇰': ['kosovo', 'flag', 'xk'],
  '🇰🇼': ['kuwait', 'flag', 'kw'],
  '🇰🇬': ['kyrgyzstan', 'flag', 'kg'],
  '🇱🇦': ['laos', 'flag', 'la'],
  '🇱🇻': ['latvia', 'flag', 'lv'],
  '🇱🇧': ['lebanon', 'flag', 'lb'],
  '🇱🇸': ['lesotho', 'flag', 'ls'],
  '🇱🇷': ['liberia', 'flag', 'lr'],
  '🇱🇾': ['libya', 'flag', 'ly'],
  '🇱🇮': ['liechtenstein', 'flag', 'li'],
  '🇱🇹': ['lithuania', 'flag', 'lt'],
  '🇱🇺': ['luxembourg', 'flag', 'lu'],
  '🇲🇴': ['macau', 'macao', 'flag', 'mo'],
  '🇲🇬': ['madagascar', 'flag', 'mg'],
  '🇲🇼': ['malawi', 'flag', 'mw'],
  '🇲🇾': ['malaysia', 'flag', 'my'],
  '🇲🇻': ['maldives', 'flag', 'mv'],
  '🇲🇱': ['mali', 'flag', 'ml'],
  '🇲🇹': ['malta', 'flag', 'mt'],
  '🇲🇭': ['marshall', 'islands', 'flag', 'mh'],
  '🇲🇷': ['mauritania', 'flag', 'mr'],
  '🇲🇺': ['mauritius', 'flag', 'mu'],
  '🇲🇽': ['mexico', 'flag', 'mx', 'mexican'],
  '🇫🇲': ['micronesia', 'flag', 'fm'],
  '🇲🇩': ['moldova', 'flag', 'md'],
  '🇲🇨': ['monaco', 'flag', 'mc'],
  '🇲🇳': ['mongolia', 'flag', 'mn'],
  '🇲🇪': ['montenegro', 'flag', 'me'],
  '🇲🇦': ['morocco', 'flag', 'ma'],
  '🇲🇿': ['mozambique', 'flag', 'mz'],
  '🇲🇲': ['myanmar', 'burma', 'flag', 'mm'],
  '🇳🇦': ['namibia', 'flag', 'na'],
  '🇳🇷': ['nauru', 'flag', 'nr'],
  '🇳🇵': ['nepal', 'flag', 'np'],
  '🇳🇱': ['netherlands', 'flag', 'nl', 'dutch', 'holland'],
  '🇳🇿': ['new', 'zealand', 'flag', 'nz', 'kiwi'],
  '🇳🇮': ['nicaragua', 'flag', 'ni'],
  '🇳🇪': ['niger', 'flag', 'ne'],
  '🇳🇬': ['nigeria', 'flag', 'ng'],
  '🇰🇵': ['north', 'korea', 'flag', 'kp', 'dprk'],
  '🇲🇰': ['north', 'macedonia', 'flag', 'mk'],
  '🇳🇴': ['norway', 'flag', 'no', 'norwegian'],
  '🇴🇲': ['oman', 'flag', 'om'],
  '🇵🇰': ['pakistan', 'flag', 'pk'],
  '🇵🇼': ['palau', 'flag', 'pw'],
  '🇵🇸': ['palestine', 'flag', 'ps'],
  '🇵🇦': ['panama', 'flag', 'pa'],
  '🇵🇬': ['papua', 'new', 'guinea', 'flag', 'pg'],
  '🇵🇾': ['paraguay', 'flag', 'py'],
  '🇵🇪': ['peru', 'flag', 'pe'],
  '🇵🇭': ['philippines', 'flag', 'ph'],
  '🇵🇱': ['poland', 'flag', 'pl', 'polish'],
  '🇵🇹': ['portugal', 'flag', 'pt', 'portuguese'],
  '🇵🇷': ['puerto', 'rico', 'flag', 'pr'],
  '🇶🇦': ['qatar', 'flag', 'qa'],
  '🇷🇴': ['romania', 'flag', 'ro'],
  '🇷🇺': ['russia', 'flag', 'ru', 'russian'],
  '🇷🇼': ['rwanda', 'flag', 'rw'],
  '🇼🇸': ['samoa', 'flag', 'ws'],
  '🇸🇲': ['san', 'marino', 'flag', 'sm'],
  '🇸🇦': ['saudi', 'arabia', 'flag', 'sa'],
  '🇸🇳': ['senegal', 'flag', 'sn'],
  '🇷🇸': ['serbia', 'flag', 'rs'],
  '🇸🇨': ['seychelles', 'flag', 'sc'],
  '🇸🇱': ['sierra', 'leone', 'flag', 'sl'],
  '🇸🇬': ['singapore', 'flag', 'sg'],
  '🇸🇰': ['slovakia', 'flag', 'sk'],
  '🇸🇮': ['slovenia', 'flag', 'si'],
  '🇸🇧': ['solomon', 'islands', 'flag', 'sb'],
  '🇸🇴': ['somalia', 'flag', 'so'],
  '🇿🇦': ['south', 'africa', 'flag', 'za'],
  '🇰🇷': ['south', 'korea', 'flag', 'kr', 'korean'],
  '🇸🇸': ['south', 'sudan', 'flag', 'ss'],
  '🇪🇸': ['spain', 'flag', 'es', 'spanish'],
  '🇱🇰': ['sri', 'lanka', 'flag', 'lk'],
  '🇸🇩': ['sudan', 'flag', 'sd'],
  '🇸🇷': ['suriname', 'flag', 'sr'],
  '🇸🇪': ['sweden', 'flag', 'se', 'swedish'],
  '🇨🇭': ['switzerland', 'flag', 'ch', 'swiss'],
  '🇸🇾': ['syria', 'flag', 'sy'],
  '🇹🇼': ['taiwan', 'flag', 'tw'],
  '🇹🇯': ['tajikistan', 'flag', 'tj'],
  '🇹🇿': ['tanzania', 'flag', 'tz'],
  '🇹🇭': ['thailand', 'flag', 'th', 'thai'],
  '🇹🇱': ['timor', 'leste', 'flag', 'tl'],
  '🇹🇬': ['togo', 'flag', 'tg'],
  '🇹🇴': ['tonga', 'flag', 'to'],
  '🇹🇹': ['trinidad', 'tobago', 'flag', 'tt'],
  '🇹🇳': ['tunisia', 'flag', 'tn'],
  '🇹🇷': ['turkey', 'flag', 'tr', 'turkish'],
  '🇹🇲': ['turkmenistan', 'flag', 'tm'],
  '🇹🇻': ['tuvalu', 'flag', 'tv'],
  '🇺🇬': ['uganda', 'flag', 'ug'],
  '🇺🇦': ['ukraine', 'flag', 'ua', 'ukrainian'],
  '🇦🇪': ['united', 'arab', 'emirates', 'uae', 'flag', 'ae'],
  '🇬🇧': ['united', 'kingdom', 'uk', 'flag', 'gb', 'british', 'england'],
  '🇺🇸': ['united', 'states', 'usa', 'flag', 'us', 'american', 'america'],
  '🇺🇾': ['uruguay', 'flag', 'uy'],
  '🇺🇿': ['uzbekistan', 'flag', 'uz'],
  '🇻🇺': ['vanuatu', 'flag', 'vu'],
  '🇻🇦': ['vatican', 'city', 'flag', 'va'],
  '🇻🇪': ['venezuela', 'flag', 've'],
  '🇻🇳': ['vietnam', 'flag', 'vn', 'vietnamese'],
  '🇾🇪': ['yemen', 'flag', 'ye'],
  '🇿🇲': ['zambia', 'flag', 'zm'],
  '🇿🇼': ['zimbabwe', 'flag', 'zw'],
};

/**
 * Search emojis by keyword
 * @param query - The search query
 * @param emojiList - List of emojis to search through
 * @returns Array of matching emojis
 */
export function searchEmojisByKeyword(
  query: string,
  emojiList?: string[]
): string[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  const results: string[] = [];
  const seen = new Set<string>();

  // If emojiList is provided, search only within that list
  const emojisToSearch = emojiList ?? Object.keys(EMOJI_KEYWORDS);

  for (const emoji of emojisToSearch) {
    if (seen.has(emoji)) continue;

    const keywords = EMOJI_KEYWORDS[emoji];
    if (keywords?.some(k => k.includes(lowerQuery))) {
      results.push(emoji);
      seen.add(emoji);
    }
  }
  return results;
}
